image: ghcr.io/cirruslabs/flutter:stable

pages:
  stage: deploy
  script:
    - flutter pub get
    # Bemærk: Vi behøver ikke cd mere. 
    # Men vi behøver stadig base-href for at URL'en virker på GitLab Pages
    - flutter build web --base-href "/TrashQueue/"
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - main